In [1]:
import numpy as np
import time

## 1. Comparison

In [25]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorization version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop version: " + str(1000*(toc-tic)) + "ms")

250126.50557589708
Vectorization version: 0.6661415100097656ms
250126.50557590416
For loop version: 331.38203620910645ms


## 2. Numpy Array Operations

In [26]:
print(a)
print(np.exp(a))
print(np.log(a))
print(np.abs(a))
print(np.max(a))  # 计算a的最大值
print(np.maximum(a,0))  # 计算a和0的最大值

[0.01866495 0.81352094 0.43856281 ... 0.43411878 0.78952949 0.90719659]
[1.01884023 2.25583669 1.55047729 ... 1.54360221 2.20235995 2.47736771]
[-3.98110784 -0.20638361 -0.82425224 ... -0.83443709 -0.23631809
 -0.0973961 ]
[0.01866495 0.81352094 0.43856281 ... 0.43411878 0.78952949 0.90719659]
0.9999999672336279
[0.01866495 0.81352094 0.43856281 ... 0.43411878 0.78952949 0.90719659]


## 3. Logistic Regression

### a. For loop version

In [ ]:
J = 0, dw1 = 0, dw2 = 0, db = 0
for i in range(1,m+1):
    